--DROP TABLE DC_DESTRUCTION;

--------------------------------------------------------
--  File created - Thursday-March-19-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DC_DESTRUCTION
--------------------------------------------------------


  CREATE TABLE "CONTENTSERVER"."DC_DESTRUCTION" 
   ("PENSION_NO" NVARCHAR2(20), 
    "DESTRUCTIO_DATE" NVARCHAR2(20) DEFAULT TO_CHAR(SYSDATE,'YYYYMMDD'),
	"STATUS_DATE" NVARCHAR2(20) DEFAULT TO_CHAR(SYSDATE,'YYYYMMDD'), 
	"STATUS" NVARCHAR2(20) DEFAULT 'Selected', 
    "NAME" VARCHAR2(60 BYTE), 
	"SURNAME" VARCHAR2(60 BYTE), 
    "GRANT_TYPE" VARCHAR2(5 BYTE),
	"REGION_ID" INTEGER DEFAULT 0,
    "EXCLUSIONBATCH_ID" INTEGER DEFAULT 0,
    "DESTRUCTION_BATCH_ID" INTEGER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 130023424 NEXT 130023424 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DC_DESTRUCTION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CONTENTSERVER"."DC_DESTRUCTION_PK" ON "CONTENTSERVER"."DC_DESTRUCTION" ("PENSION_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 130023424 NEXT 130023424 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table DC_DESTRUCTION
--------------------------------------------------------

  ALTER TABLE "CONTENTSERVER"."DC_DESTRUCTION" MODIFY ("PENSION_NO" NOT NULL ENABLE);
  ALTER TABLE "CONTENTSERVER"."DC_DESTRUCTION" MODIFY ("STATUS_DATE" NOT NULL ENABLE);
  ALTER TABLE "CONTENTSERVER"."DC_DESTRUCTION" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "CONTENTSERVER"."DC_DESTRUCTION" ADD CONSTRAINT "DC_DESTRUCTION_PK" PRIMARY KEY ("PENSION_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 130023424 NEXT 130023424 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CONTENTSERVER"."DC_DESTRUCTION" MODIFY ("REGION_ID" NOT NULL ENABLE);

commit;