--------------------------------------------------------
--  DDL for Table DC_EXCLUSION_BATCH
--------------------------------------------------------


  CREATE TABLE "CONTENTSERVER"."DC_EXCLUSION_BATCH" 
   (	"BATCH_ID" INTEGER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"REGION_ID" INTEGER DEFAULT 0, 
    "EXCLUSION_YEAR" VARCHAR2(10),
	"CREATED_BY" VARCHAR2(20 BYTE), 
	"CREATED_DATE" VARCHAR2(8 BYTE) DEFAULT TO_CHAR(SYSDATE,'YYYYMMDD'), 
	"APPROVED_BY" VARCHAR2(20 BYTE), 
	"APPROVED_DATE" VARCHAR2(8 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "CONTENTSERVER" ;
--------------------------------------------------------
--  DDL for Index DC_EXCLUSION_BATCH_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CONTENTSERVER"."DC_EXCLUSION_BATCH_PK" ON "CONTENTSERVER"."DC_EXCLUSION_BATCH" ("BATCH_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "CONTENTSERVER" ;
--------------------------------------------------------
--  Constraints for Table DC_EXCLUSION_BATCH
--------------------------------------------------------

  ALTER TABLE "CONTENTSERVER"."DC_EXCLUSION_BATCH" MODIFY ("BATCH_ID" NOT NULL ENABLE);
  ALTER TABLE "CONTENTSERVER"."DC_EXCLUSION_BATCH" ADD CONSTRAINT "DC_EXCLUSION_BATCH_PK" PRIMARY KEY ("BATCH_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "CONTENTSERVER"  ENABLE;
  
  
  --------------------------------------------------------
--  DDL for Table DC_DESTRUCTION_BATCH
--------------------------------------------------------

  CREATE TABLE "CONTENTSERVER"."DC_DESTRUCTION_BATCH" 
   (	"BATCH_ID" INTEGER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"REGION_ID" INTEGER DEFAULT 0, 
    "DESTRUCTION_YEAR" VARCHAR2(10),
	"CREATED_BY" VARCHAR2(20 BYTE), 
	"CREATED_DATE" VARCHAR2(8 BYTE) DEFAULT TO_CHAR(SYSDATE,'YYYYMMDD'), 
	"APPROVED_BY" VARCHAR2(20 BYTE), 
	"APPROVED_DATE" VARCHAR2(8 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "CONTENTSERVER" ;
--------------------------------------------------------
--  DDL for Index DC_DESTRUCTION_BATCH_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CONTENTSERVER"."DC_DESTRUCTION_BATCH_PK" ON "CONTENTSERVER"."DC_DESTRUCTION_BATCH" ("BATCH_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "CONTENTSERVER" ;
--------------------------------------------------------
--  Constraints for Table DC_DESTRUCTION_BATCH
--------------------------------------------------------

  ALTER TABLE "CONTENTSERVER"."DC_DESTRUCTION_BATCH" MODIFY ("BATCH_ID" NOT NULL ENABLE);
  ALTER TABLE "CONTENTSERVER"."DC_DESTRUCTION_BATCH" ADD CONSTRAINT "DC_DESTRUCTION_BATCH_PK" PRIMARY KEY ("BATCH_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "CONTENTSERVER"  ENABLE;

