--------------------------------------------------------
--  DDL for Table DC_EXCLUSIONS
--------------------------------------------------------

  CREATE TABLE "CONTENTSERVER"."DC_EXCLUSIONS" 
   ("ID_NO" VARCHAR2(20 BYTE), 
	"EXCL_DATE" DATE, 
	"REGION_ID" NUMBER(*,0), 
	"USERNAME" NVARCHAR2(40), 
	"EXCLUSION_TYPE" NVARCHAR2(20), 
	"EXCLUSION_BATCH_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CONTENTSERVER" ;
--------------------------------------------------------
--  DDL for Index PRIMARYKEY
--------------------------------------------------------

  CREATE UNIQUE INDEX "CONTENTSERVER"."PRIMARYKEY" ON "CONTENTSERVER"."DC_EXCLUSIONS" ("ID_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 130023424 NEXT 130023424 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table DC_EXCLUSIONS
--------------------------------------------------------

  ALTER TABLE "CONTENTSERVER"."DC_EXCLUSIONS" MODIFY ("ID_NO" NOT NULL ENABLE);
  ALTER TABLE "CONTENTSERVER"."DC_EXCLUSIONS" MODIFY ("REGION_ID" NOT NULL ENABLE);
  ALTER TABLE "CONTENTSERVER"."DC_EXCLUSIONS" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "CONTENTSERVER"."DC_EXCLUSIONS" MODIFY ("EXCLUSION_TYPE" NOT NULL ENABLE);
  ALTER TABLE "CONTENTSERVER"."DC_EXCLUSIONS" ADD CONSTRAINT "DC_EXCLUSIONS_PK" PRIMARY KEY ("ID_NO")
  USING INDEX (CREATE UNIQUE INDEX "CONTENTSERVER"."PRIMARYKEY" ON "CONTENTSERVER"."DC_EXCLUSIONS" ("ID_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 130023424 NEXT 130023424 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" )  ENABLE;
