--Remove duplicates
DELETE FROM DC_DESTRUCTION_LIST
WHERE rowid not in (SELECT MIN(rowid) FROM DC_DESTRUCTION_LIST GROUP BY PENSION_NO);
--Extract working list
INSERT INTO DC_DESTRUCTION d (PENSION_NO,DESTRUCTIO_DATE,REGION_ID, STATUS_DATE, STATUS, NAME, SURNAME )
SELECT PENSION_NO,STATUS_DATE,REGION, TO_CHAR(SYSDATE,'YYYYMMDD'),'TDWNotFound',dl.name, dl.SURNAME
FROM DC_DESTRUCTION_LIST dl 
WHERE dl.PENSION_NO NOT IN(SELECT PENSION_NO FROM DC_DESTRUCTION);
--Update old records
Update DC_DESTRUCTION D 
SET DESTRUCTIO_DATE = '00000101'
WHERE TO_NUMBER(SUBSTR(DESTRUCTIO_DATE,0,4)) < 2004;
--Update TDWStatus
Update DC_DESTRUCTION D 
SET Status =  'TDWFound'
where PENSION_NO IN(select DESCRIPTION from TDW_FILE_LOCATION);
COMMIT;