//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SASSADirectCapture.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUST_LOCALOFFICE
    {
        public decimal LOCALID { get; set; }
        public string LOCALOFFICE { get; set; }
        public Nullable<decimal> DISTRICTID { get; set; }
    
        public virtual CUST_DISTRICT CUST_DISTRICT { get; set; }
    }
}
