//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SASSADirectCapture.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUST_DISTRICT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUST_DISTRICT()
        {
            this.CUST_LOCALOFFICE = new HashSet<CUST_LOCALOFFICE>();
        }
    
        public decimal DISTRICTID { get; set; }
        public string DISTRICT { get; set; }
        public string REGNUM { get; set; }
    
        public virtual CUST_REGIONS CUST_REGIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUST_LOCALOFFICE> CUST_LOCALOFFICE { get; set; }
    }
}
