//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SASSADirectCapture.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_ACTIVITY
    {
        public decimal DC_ACTIVITY_ID { get; set; }
        public string USERNAME { get; set; }
        public string AREA { get; set; }
        public string ACTIVITY { get; set; }
        public string RESULT { get; set; }
        public Nullable<decimal> USERID { get; set; }
        public System.DateTime ACTIVITY_DATE { get; set; }
        public string REGION_ID { get; set; }
        public decimal OFFICE_ID { get; set; }
        public string UNQ_FILE_NO { get; set; }
    }
}
