//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SASSADirectCapture.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_BOX_TYPE
    {
        public decimal BOX_TYPE_ID { get; set; }
        public string BOX_TYPE { get; set; }
        public string IS_TRANSPORT { get; set; }
    }
}
