//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SASSADirectCapture.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_BATCH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DC_BATCH()
        {
            this.DC_FILE = new HashSet<DC_FILE>();
        }
    
        public decimal BATCH_NO { get; set; }
        public string OFFICE_ID { get; set; }
        public decimal UPDATED_BY { get; set; }
        public System.DateTime UPDATED_DATE { get; set; }
        public string BATCH_CURRENT { get; set; }
        public string BATCH_STATUS { get; set; }
        public string BATCH_COMMENT { get; set; }
        public string WAYBILL_NO { get; set; }
        public string COURIER_NAME { get; set; }
        public Nullable<System.DateTime> WAYBILL_DATE { get; set; }
        public string UPDATED_BY_AD { get; set; }
        public string REG_TYPE { get; set; }
    
        public virtual DC_LOCAL_OFFICE DC_LOCAL_OFFICE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DC_FILE> DC_FILE { get; set; }
    }
}
