//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SASSADirectCapture.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_BOXPICKED
    {
        public string UNQ_PICKLIST { get; set; }
        public string BIN_NUMBER { get; set; }
        public string BOX_NUMBER { get; set; }
        public string BOX_RECEIVED { get; set; }
        public string BOX_COMPLETED { get; set; }
        public string ARCHIVE_YEAR { get; set; }
        public string UNQ_NO { get; set; }
    }
}
