//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SASSADirectCapture.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_DESTRUCTION
    {
        public string PENSION_NO { get; set; }
        public string DESTRUCTIO_DATE { get; set; }
        public string STATUS_DATE { get; set; }
        public string STATUS { get; set; }
        public string NAME { get; set; }
        public string SURNAME { get; set; }
        public string GRANT_TYPE { get; set; }
        public decimal REGION_ID { get; set; }
        public Nullable<decimal> EXCLUSIONBATCH_ID { get; set; }
        public Nullable<decimal> DESTRUCTION_BATCH_ID { get; set; }
    }
}
