//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SASSADirectCapture.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_EXCLUSIONS
    {
        public string ID_NO { get; set; }
        public Nullable<System.DateTime> EXCL_DATE { get; set; }
        public decimal REGION_ID { get; set; }
        public string USERNAME { get; set; }
        public string EXCLUSION_TYPE { get; set; }
        public Nullable<decimal> EXCLUSION_BATCH_ID { get; set; }
    }
}
