//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SASSADirectCapture.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_FILE_REQUEST
    {
        public string UNQ_FILE_NO { get; set; }
        public string ID_NO { get; set; }
        public string MIS_FILE_NO { get; set; }
        public string NAME { get; set; }
        public string SURNAME { get; set; }
        public string REGION_ID { get; set; }
        public Nullable<decimal> REQUESTED_BY { get; set; }
        public Nullable<System.DateTime> REQUESTED_DATE { get; set; }
        public string REQUESTED_OFFICE_ID { get; set; }
        public Nullable<decimal> SCANNED_BY { get; set; }
        public Nullable<System.DateTime> SCANNED_DATE { get; set; }
        public Nullable<System.DateTime> CLOSED_DATE { get; set; }
        public Nullable<decimal> CLOSED_BY { get; set; }
        public string RELATED_MIS_FILE_NO { get; set; }
        public string GRANT_TYPE { get; set; }
        public Nullable<System.DateTime> APP_DATE { get; set; }
        public string SCANNED_PHYSICAL_IND { get; set; }
        public Nullable<decimal> REQ_CATEGORY { get; set; }
        public Nullable<decimal> REQ_CATEGORY_TYPE { get; set; }
        public string REQ_CATEGORY_DETAIL { get; set; }
        public string BRM_BARCODE { get; set; }
        public string BIN_ID { get; set; }
        public string BOX_NUMBER { get; set; }
        public string POSITION { get; set; }
        public string TDW_BOXNO { get; set; }
        public string SENT_TDW { get; set; }
        public string RECEIVED_TDW { get; set; }
        public string FILE_RETRIEVED { get; set; }
        public string SEND_TO_REQUESTOR { get; set; }
        public Nullable<decimal> PICKLIST_NO { get; set; }
        public string PICKLIST_TYPE { get; set; }
        public string PICKLIST_STATUS { get; set; }
        public string PICKED_BY { get; set; }
        public string CLM_NUMBER { get; set; }
        public string REGION_ID_TO { get; set; }
        public Nullable<decimal> STAKEHOLDER { get; set; }
        public string SERV_BY { get; set; }
        public string REQUESTED_BY_AD { get; set; }
        public string SCANNED_BY_AD { get; set; }
        public string CLOSED_BY_AD { get; set; }
        public string APPLICATION_STATUS { get; set; }
    
        public virtual DC_STAKEHOLDER DC_STAKEHOLDER { get; set; }
        public virtual DC_REGION DC_REGION { get; set; }
        public virtual DC_REQ_CATEGORY_TYPE_LINK DC_REQ_CATEGORY_TYPE_LINK { get; set; }
    }
}
