//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SASSADirectCapture.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_GRANT_DOC_LINK
    {
        public string GRANT_ID { get; set; }
        public decimal TRANSACTION_ID { get; set; }
        public decimal DOCUMENT_ID { get; set; }
        public string CRITICAL_FLAG { get; set; }
        public string SECTION { get; set; }
    
        public virtual DC_DOCUMENT_TYPE DC_DOCUMENT_TYPE { get; set; }
        public virtual DC_TRANSACTION_TYPE DC_TRANSACTION_TYPE { get; set; }
        public virtual DC_GRANT_TYPE DC_GRANT_TYPE { get; set; }
    }
}
