//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SASSADirectCapture.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_LOCAL_OFFICE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DC_LOCAL_OFFICE()
        {
            this.DC_BATCH = new HashSet<DC_BATCH>();
            this.DC_FILE = new HashSet<DC_FILE>();
            this.DC_OFFICE_KUAF_LINK = new HashSet<DC_OFFICE_KUAF_LINK>();
        }
    
        public string OFFICE_ID { get; set; }
        public string OFFICE_NAME { get; set; }
        public string REGION_ID { get; set; }
        public string OFFICE_TYPE { get; set; }
        public string DISTRICT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DC_BATCH> DC_BATCH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DC_FILE> DC_FILE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DC_OFFICE_KUAF_LINK> DC_OFFICE_KUAF_LINK { get; set; }
        public virtual DC_REGION DC_REGION { get; set; }
    }
}
