//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SASSADirectCapture.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_MERGE
    {
        public decimal PK { get; set; }
        public string BRM_BARCODE { get; set; }
        public string PARENT_BRM_BARCODE { get; set; }
    }
}
