//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SASSADirectCapture.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_REGION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DC_REGION()
        {
            this.DC_LOCAL_OFFICE = new HashSet<DC_LOCAL_OFFICE>();
            this.DC_FILE_REQUEST = new HashSet<DC_FILE_REQUEST>();
            this.DC_STAKEHOLDER = new HashSet<DC_STAKEHOLDER>();
        }
    
        public string REGION_ID { get; set; }
        public string REGION_NAME { get; set; }
        public string REGION_CODE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DC_LOCAL_OFFICE> DC_LOCAL_OFFICE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DC_FILE_REQUEST> DC_FILE_REQUEST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DC_STAKEHOLDER> DC_STAKEHOLDER { get; set; }
    }
}
