//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SASSADirectCapture.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_REQ_CATEGORY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DC_REQ_CATEGORY()
        {
            this.DC_REQ_CATEGORY_TYPE_LINK = new HashSet<DC_REQ_CATEGORY_TYPE_LINK>();
            this.DC_STAKEHOLDER = new HashSet<DC_STAKEHOLDER>();
        }
    
        public decimal CATEGORY_ID { get; set; }
        public string CATEGORY_DESCR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DC_REQ_CATEGORY_TYPE_LINK> DC_REQ_CATEGORY_TYPE_LINK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DC_STAKEHOLDER> DC_STAKEHOLDER { get; set; }
    }
}
