//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SASSADirectCapture.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_STAKEHOLDER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DC_STAKEHOLDER()
        {
            this.DC_FILE_REQUEST = new HashSet<DC_FILE_REQUEST>();
        }
    
        public decimal STAKEHOLDER_ID { get; set; }
        public decimal DEPARTMENT_ID { get; set; }
        public string NAME { get; set; }
        public string SURNAME { get; set; }
        public string EMAIL { get; set; }
        public string REGION_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DC_FILE_REQUEST> DC_FILE_REQUEST { get; set; }
        public virtual DC_REQ_CATEGORY DC_REQ_CATEGORY { get; set; }
        public virtual DC_REGION DC_REGION { get; set; }
    }
}
