//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SASSADirectCapture.EntityModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CUST_DISTRICT> CUST_DISTRICT { get; set; }
        public DbSet<CUST_LOCALOFFICE> CUST_LOCALOFFICE { get; set; }
        public DbSet<CUST_REGIONS> CUST_REGIONS { get; set; }
        public DbSet<DC_BATCH> DC_BATCH { get; set; }
        public DbSet<DC_DOCUMENT_TYPE> DC_DOCUMENT_TYPE { get; set; }
        public DbSet<DC_FILE> DC_FILE { get; set; }
        public DbSet<DC_GRANT_DOC_LINK> DC_GRANT_DOC_LINK { get; set; }
        public DbSet<DC_GRANT_TYPE> DC_GRANT_TYPE { get; set; }
        public DbSet<DC_LOCAL_OFFICE> DC_LOCAL_OFFICE { get; set; }
        public DbSet<DC_OFFICE_KUAF_LINK> DC_OFFICE_KUAF_LINK { get; set; }
        public DbSet<DC_REGION> DC_REGION { get; set; }
        public DbSet<DC_REQ_CATEGORY> DC_REQ_CATEGORY { get; set; }
        public DbSet<DC_REQ_CATEGORY_TYPE> DC_REQ_CATEGORY_TYPE { get; set; }
        public DbSet<DC_REQ_CATEGORY_TYPE_LINK> DC_REQ_CATEGORY_TYPE_LINK { get; set; }
        public DbSet<DC_TRANSACTION_TYPE> DC_TRANSACTION_TYPE { get; set; }
        public DbSet<KUAFCHILDREN> KUAFCHILDRENs { get; set; }
        public DbSet<DC_PICKLIST> DC_PICKLIST { get; set; }
        public DbSet<DC_DISTRICT> DC_DISTRICT { get; set; }
        public DbSet<DC_BOXPICKED> DC_BOXPICKED { get; set; }
        public DbSet<DC_BOXPICKLIST> DC_BOXPICKLIST { get; set; }
        public DbSet<DC_DISTRICT_EC> DC_DISTRICT_EC { get; set; }
        public DbSet<SOCPENBRM> SOCPENBRMs { get; set; }
        public DbSet<DC_BOX_TYPE> DC_BOX_TYPE { get; set; }
        public DbSet<DC_FILE_REQUEST> DC_FILE_REQUEST { get; set; }
        public DbSet<DC_STAKEHOLDER> DC_STAKEHOLDER { get; set; }
        public DbSet<DC_MERGE> DC_MERGE { get; set; }
        public DbSet<DC_LC_TYPE> DC_LC_TYPE { get; set; }
        public DbSet<DC_ACTIVITY> DC_ACTIVITY { get; set; }
        public DbSet<DC_DESTRUCTION> DC_DESTRUCTION { get; set; }
        public DbSet<DC_EXCLUSIONS> DC_EXCLUSIONS { get; set; }
        public DbSet<DC_DESTRUCTION_BATCH> DC_DESTRUCTION_BATCH { get; set; }
        public DbSet<DC_EXCLUSION_BATCH> DC_EXCLUSION_BATCH { get; set; }
        public DbSet<SS_APPLICATION> SS_APPLICATION { get; set; }
        public DbSet<KUAF> KUAFs { get; set; }
    }
}
