//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SASSADirectCapture.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class KUAF
    {
        public long ID { get; set; }
        public long OWNERID { get; set; }
        public long TYPE { get; set; }
        public long SPACEID { get; set; }
        public string NAME { get; set; }
        public string USERDATA { get; set; }
        public Nullable<long> LEADERID { get; set; }
        public Nullable<byte> DELETED { get; set; }
        public string USERPWD { get; set; }
        public Nullable<long> GROUPID { get; set; }
        public Nullable<int> USERPRIVILEGES { get; set; }
        public string LASTNAME { get; set; }
        public string MIDDLENAME { get; set; }
        public string FIRSTNAME { get; set; }
        public string MAILADDRESS { get; set; }
        public string CONTACT { get; set; }
        public string TITLE { get; set; }
        public Nullable<System.DateTime> PWDEXPIREDATE { get; set; }
        public Nullable<int> PWDEXPIREMODE { get; set; }
        public Nullable<short> SETTINGSNUM { get; set; }
        public string FAX { get; set; }
        public string OFFICELOCATION { get; set; }
        public Nullable<short> TIMEZONE { get; set; }
        public Nullable<long> PHOTOID { get; set; }
        public Nullable<byte> GENDER { get; set; }
        public Nullable<System.DateTime> BIRTHDAY { get; set; }
        public string PERSONALEMAIL { get; set; }
        public string HOMEADDRESS1 { get; set; }
        public string HOMEADDRESS2 { get; set; }
        public string HOMEPHONE { get; set; }
        public string HOMEFAX { get; set; }
        public string CELLULARPHONE { get; set; }
        public string PAGER { get; set; }
        public string HOMEPAGE { get; set; }
        public string FAVORITES1 { get; set; }
        public string FAVORITES2 { get; set; }
        public string FAVORITES3 { get; set; }
        public string INTERESTS { get; set; }
    }
}
