//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SASSADirectCapture.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOCPENBRM
    {
        public string FILE_TYPE { get; set; }
        public string REC_TYPE { get; set; }
        public string PENSION_NO { get; set; }
        public string PAYPOINT { get; set; }
        public string GRANT_TYPE1 { get; set; }
        public string GRANT_TYPE2 { get; set; }
        public string GRANT_TYPE3 { get; set; }
        public string GRANT_TYPE4 { get; set; }
        public string PRIM_STATUS1 { get; set; }
        public string PRIM_STATUS2 { get; set; }
        public string PRIM_STATUS3 { get; set; }
        public string PRIM_STATUS4 { get; set; }
        public string SEC_STATUS1 { get; set; }
        public string SEC_STATUS2 { get; set; }
        public string SEC_STATUS3 { get; set; }
        public string SEC_STATUS4 { get; set; }
        public string STATUS_DATE1 { get; set; }
        public string STATUS_DATE2 { get; set; }
        public string STATUS_DATE3 { get; set; }
        public string STATUS_DATE4 { get; set; }
        public string APP_DATE1 { get; set; }
        public string APP_DATE2 { get; set; }
        public string APP_DATE3 { get; set; }
        public string APP_DATE4 { get; set; }
        public string REVIEW_CODE1 { get; set; }
        public string REVIEW_CODE2 { get; set; }
        public string REVIEW_CODE3 { get; set; }
        public string REVIEW_CODE4 { get; set; }
        public string STATUS_REASON1 { get; set; }
        public string STATUS_REASON2 { get; set; }
        public string STATUS_REASON3 { get; set; }
        public string STATUS_REASON4 { get; set; }
        public string STAT_PER1 { get; set; }
        public string STAT_PER2 { get; set; }
        public string STAT_PER3 { get; set; }
        public string STAT_PER4 { get; set; }
        public string DATE_ACCEPT1 { get; set; }
        public string DATE_ACCEPT2 { get; set; }
        public string DATE_ACCEPT3 { get; set; }
        public string DATE_ACCEPT4 { get; set; }
        public string ORIG_APP_DATE1 { get; set; }
        public string ORIG_APP_DATE2 { get; set; }
        public string ORIG_APP_DATE3 { get; set; }
        public string ORIG_APP_DATE4 { get; set; }
        public string OLD_ID1 { get; set; }
        public string OLD_ID2 { get; set; }
        public string OLD_ID3 { get; set; }
        public string OLD_ID4 { get; set; }
        public string OLD_ID5 { get; set; }
        public string OLD_ID6 { get; set; }
        public string OLD_ID7 { get; set; }
        public string OLD_ID8 { get; set; }
        public string OLD_ID9 { get; set; }
        public string OLD_ID10 { get; set; }
        public string BRANCH { get; set; }
        public string SURNAME { get; set; }
        public string NAME { get; set; }
        public string ADDRESS { get; set; }
        public string POSTAL_ADDRESS { get; set; }
        public string POSTAL_CODE { get; set; }
        public string NO_KIDS { get; set; }
        public string PAYMENT_METHOD { get; set; }
        public string SEX { get; set; }
        public string MARITAL_STATUS { get; set; }
        public string BIRTHDATE { get; set; }
        public string KIDS_INVOLVED { get; set; }
        public string NO_CARE_DEP { get; set; }
        public string ACCOUNT_NO { get; set; }
        public string SEC_PAYPOINT { get; set; }
        public string PAYMENT_MODE { get; set; }
        public string RE_REGISTERED { get; set; }
        public string NO_KIDS_OWN { get; set; }
        public string NO_KIDS_OTHER { get; set; }
        public string PROVINCE { get; set; }
        public string TELNO { get; set; }
        public string CELLNO { get; set; }
        public string REVIEWPERIOD { get; set; }
        public string MEDICALPERIOD { get; set; }
        public string LIFECERTPERIOD { get; set; }
        public string DOCS_PRESENT { get; set; }
    }
}
