//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SASSADirectCapture.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SS_APPLICATION
    {
        public Nullable<int> APP_ID { get; set; }
        public string FORM_NUMBER { get; set; }
        public string ID_NUMBER { get; set; }
        public string SOCPEN_ID_NUMBER { get; set; }
        public string ALT_ID_NUMBER_1 { get; set; }
        public string ALT_ID_NUMBER_2 { get; set; }
        public string ALT_ID_NUMBER_3 { get; set; }
        public string SURNAME { get; set; }
        public string NAME { get; set; }
        public string APPLICATION_DATE { get; set; }
        public string GRANT_TYPE { get; set; }
        public string FORM_TYPE { get; set; }
        public string DISABILITY_TYPE { get; set; }
        public string DISABILITY_DESC { get; set; }
        public string MED_FORM { get; set; }
        public string DOC_NAME { get; set; }
        public string GENDER { get; set; }
        public Nullable<int> RACE { get; set; }
        public string PAYPOINT { get; set; }
        public Nullable<int> TOWN { get; set; }
        public string REGION_CODE { get; set; }
        public Nullable<int> SERVICE_ID { get; set; }
        public string DISTRICT_OFFICE { get; set; }
        public string BOX { get; set; }
        public string POSITN { get; set; }
        public string A_YEAR { get; set; }
        public string BOX_TYPE { get; set; }
        public string LETTER_GEN_DATE { get; set; }
        public string LETTER_SENT_DATE { get; set; }
        public string ON_PERSAL { get; set; }
        public string ON_GEPF { get; set; }
        public string ON_MUNI { get; set; }
        public string PERSAL_NO { get; set; }
        public string APPL_STATUS { get; set; }
        public string DATE_IN { get; set; }
        public string ACTION_DATE { get; set; }
        public string ACTION_RESULT { get; set; }
        public string REASON { get; set; }
        public string MATCH_TYPE { get; set; }
        public string REGISTRY_REMOVAL { get; set; }
        public string APPLICATION_DOC { get; set; }
        public string ID_BOOK { get; set; }
        public string MEDICAL_CERT { get; set; }
        public string BIRTH_CERT { get; set; }
        public string COURT_ORD { get; set; }
        public string WAR_PAPERS { get; set; }
        public string USER_ID_CREATED { get; set; }
        public Nullable<int> OLD_POSITION { get; set; }
        public Nullable<long> APPROVED_AMOUNT { get; set; }
        public Nullable<long> ONE_OFF_PAYMENT { get; set; }
        public string PAYMENT_DATE { get; set; }
        public Nullable<int> DC_PERSAL_NO { get; set; }
        public string DC_ACTION { get; set; }
        public string DC_ACTION_DATE { get; set; }
        public string DC_COMPLETE { get; set; }
        public string LETTER { get; set; }
        public string LETTER_MEMO { get; set; }
        public string COPY_PRINT_DATE { get; set; }
        public string BANKNAME { get; set; }
        public string ANNEXURE_A { get; set; }
        public string ANNEXURE_B { get; set; }
        public string HOME_AFFAIRS_REF1 { get; set; }
        public string HOME_AFFAIRS_REF2 { get; set; }
        public Nullable<bool> ID_DOC { get; set; }
        public Nullable<bool> PROOF_ID { get; set; }
        public Nullable<bool> BIRTH_CERTIFICATE { get; set; }
        public Nullable<bool> PROOF_BIRTH { get; set; }
        public string SOCPEN_REF { get; set; }
        public Nullable<bool> REFUGEE_GRANT { get; set; }
        public string DATE_EXPIRY_OF_TEMP_ID { get; set; }
        public Nullable<int> PAYMENT_METHOD { get; set; }
        public string CLIENT_DOB { get; set; }
        public Nullable<bool> FLAG_ADMIN_REVIEW { get; set; }
        public Nullable<bool> QA_AMENDMENTS { get; set; }
        public string VERSION { get; set; }
        public Nullable<int> SERVICE_POINT_ID { get; set; }
    }
}
